version: '3.7'

networks:
  privasee-net:

services:
  frontend:
    container_name: privasee_frontend
    build:
      context: ./
      dockerfile: docker/frontend-Dockerfile
    ports:
      - "15000:15000"
    networks:
      privasee-net:

  backend:
    container_name: privasee_backend
    build:
      context: ./
      dockerfile: docker/backend-Dockerfile
    ports:
      - "18000:18000"
    environment:
      DATABASE_URL: "/opt/speedtest/database/privasee.db"
      MIDDLEWEAR_PORT: "18000"
    networks:
      privasee-net: